version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "3002:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_CONNECT_TIMEOUT: ${MONGO_INITDB_CONNECT_TIMEOUT}
    restart: always

volumes:
  mongo_data: 
